name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    name: Test Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Run test cases
        run: dotnet test
